[package]
name = "sendSimpleUdp"
version = "0.1.0"
authors = ["analyman <beam.analyman@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name="ssend"
path="src/ssend/main.rs"

[[bin]]
name="sreply"
path="src/sreply/main.rs"

[dependencies]

